"""empty message

Revision ID: 8624cbb5fd4e
Revises: 
Create Date: 2023-07-20 19:33:58.692839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8624cbb5fd4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContactUs',
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Message', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('CountryInfo',
    sa.Column('CommonName', sa.String(length=255), nullable=False),
    sa.Column('OfficialName', sa.String(length=255), nullable=False),
    sa.Column('CountryCode', sa.String(length=64), nullable=False),
    sa.Column('Info', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('IPV4',
    sa.Column('StartRange', sa.BIGINT(), nullable=False),
    sa.Column('EndRange', sa.BIGINT(), nullable=False),
    sa.Column('CountryCode', sa.String(length=64), nullable=False),
    sa.Column('CountryName', sa.String(length=64), nullable=False),
    sa.Column('StateName', sa.String(length=64), nullable=False),
    sa.Column('CityName', sa.String(length=64), nullable=False),
    sa.Column('Lat', sa.String(length=64), nullable=False),
    sa.Column('Long', sa.String(length=64), nullable=False),
    sa.Column('ZipCode', sa.String(length=64), nullable=False),
    sa.Column('TimeZone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EndRange'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('IPV6',
    sa.Column('StartRange', sa.DECIMAL(precision=36, scale=0), nullable=False),
    sa.Column('EndRange', sa.DECIMAL(precision=36, scale=0), nullable=False),
    sa.Column('CountryCode', sa.String(length=64), nullable=False),
    sa.Column('CountryName', sa.String(length=64), nullable=False),
    sa.Column('StateName', sa.String(length=64), nullable=False),
    sa.Column('CityName', sa.String(length=64), nullable=False),
    sa.Column('Lat', sa.String(length=64), nullable=False),
    sa.Column('Long', sa.String(length=64), nullable=False),
    sa.Column('ZipCode', sa.String(length=64), nullable=False),
    sa.Column('TimeZone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EndRange'),
    sa.UniqueConstraint('PublicKey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IPV6')
    op.drop_table('IPV4')
    op.drop_table('CountryInfo')
    op.drop_table('ContactUs')
    # ### end Alembic commands ###
